# See https://github.com/pypa/manylinux for more information
FROM quay.io/pypa/musllinux_1_2_x86_64

ENV PYTHON_PATH=/opt/python/cp310-cp310
ENV PYTHON_EXECUTABLE=${PYTHON_PATH}/bin/python3.10

COPY ./deps /tmp/deps

RUN ${PYTHON_EXECUTABLE} -m pip install -r /tmp/deps/requirements.txt

RUN rm -rf /tmp/deps

WORKDIR /hyperon_das_atomdb_cpp

CMD ["bash", "-x", "./scripts/_build_musl_wheel.sh"]