name: Publish to PyPI

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to tag"
        required: true

jobs:
  publish-cpp:
    environment: prod
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ~3.10

      - name: Install requirements
        run: |-
          pip install twine

      - name: Install requirements
        run: |-
           pip install twine

      - name: Update version
        working-directory: hyperon_das_atomdb_cpp
        run: sed -i 's/version = ".*"/version = "${{ github.event.inputs.version }}"/' pyproject.toml

      - name: Build Wheels
        working-directory: hyperon_das_atomdb_cpp
        run: make wheels

      - name: Publish Packages
        working-directory: hyperon_das_atomdb_cpp/dist
        run: twine upload *.whl --username __token__ --password ${{ secrets.PYPI_API_TOKEN }} --non-interactive
